/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.swingteam.views;

import com.swingteam.model.HocPhiModel;
import com.swingteam.model.NhanVienModel;
import com.swingteam.model.TreModel;
import com.swingteam.service.HocPhiService;
import com.swingteam.service.TreSerVice;
import com.swingteam.service.impl.NhanVienService;
import java.io.IOException;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ngova
 */
public class HocPhiPanel extends javax.swing.JPanel {

    /**
     * Creates new form HocPhiPanel
     */
    HocPhiService hocPhiService;
    HocPhiModel hocPhiModel;
    DefaultTableModel deTableModel;
    TreModel treModel;
    TreSerVice treSerVice;
    NhanVienModel nhanVienModel;
    NhanVienService nhanVienService;
    public HocPhiPanel() {
        initComponents();
        txtMaHP.setEnabled(false);
        hocPhiService= new HocPhiService();
        nhanVienService = new NhanVienService();
        treModel= new TreModel();
        treSerVice= new TreSerVice();
        hocPhiModel= new HocPhiModel();
        nhanVienModel= new NhanVienModel();
        deTableModel= new DefaultTableModel();
        tableHP.setModel(deTableModel);
        deTableModel.addColumn("Mã học phí");
        deTableModel.addColumn("Ngày thu");
        deTableModel.addColumn("Tiền học phí");
        deTableModel.addColumn("Tiền đã đóng");
        deTableModel.addColumn("Tình trạng");
        deTableModel.addColumn("Mã trẻ");
        deTableModel.addColumn("Mã phụ huynh");
        List<HocPhiModel> hPhi= hocPhiService.getHocPHi();
        for(HocPhiModel hocPhi : hPhi){
            deTableModel.addRow(new Object[]{hocPhi.getMaHP(), hocPhi.getNgayThu(), hocPhi.getTienHP(), hocPhi.getTienDaDong(), hocPhi.getTtrang(), hocPhi.getMaTre(), hocPhi.getManv()});
        }
        List<TreModel> tres= treSerVice.getTre();
        for(TreModel tre : tres){
            cbMatre.addItem(tre.getMatre());
        }
        List<NhanVienModel> nvs= nhanVienService.findAll();
        for(NhanVienModel nv : nvs){
            cbNV.addItem(nv.getMaNhanVien());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        printButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableHP = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rbDatt = new javax.swing.JRadioButton();
        rbChuatt = new javax.swing.JRadioButton();
        txtMaHP = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtHPDD = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtHP = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtNgaythu = new com.toedter.calendar.JDateChooser();
        cbMatre = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cbNV = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        editButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/swingteam/img/edit.png"))); // NOI18N
        editButton.setText("Chỉnh sửa");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/swingteam/img/remove.png"))); // NOI18N
        deleteButton.setText("Xóa");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        printButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/swingteam/img/print-131964753156480777.png"))); // NOI18N
        printButton.setText("In hóa đơn");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        tableHP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableHPMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableHP);

        jPanel1.setBackground(new java.awt.Color(0, 204, 153));

        jLabel5.setText("Mã học phí");

        jLabel4.setText("Tình trạng :");

        rbDatt.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbDatt);
        rbDatt.setText("Đã thanh toán");

        rbChuatt.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbChuatt);
        rbChuatt.setText("Chưa thanh toán");

        jLabel6.setText("Tổng tiền đã thanh toán :");

        jLabel8.setText(".vnd");

        jLabel10.setText("Ngày thu :");

        jLabel13.setText("Học phí :");

        jLabel14.setText(".vnd");

        jLabel17.setText("Mã trẻ :");

        jLabel1.setText("Mã NV:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(cbMatre, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(txtMaHP, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel4))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtHP, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel14))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rbChuatt)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbDatt))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtHPDD, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNgaythu, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbNV, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 337, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cbMatre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rbChuatt)
                    .addComponent(rbDatt))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtHPDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(txtNgaythu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel7.setText("Học phí");

        addButton.setBackground(new java.awt.Color(255, 255, 255));
        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/swingteam/img/add.png"))); // NOI18N
        addButton.setText("Thêm");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(587, 587, 587)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addButton)
                                .addGap(50, 50, 50)
                                .addComponent(editButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(printButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(printButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(editButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        if(txtHP.getText().isEmpty()||txtHPDD.getText().isEmpty())
            JOptionPane.showMessageDialog(printButton, "Chưa nhập đủ thông tin");
        else{
              hocPhiModel.setMaHP("");
        hocPhiModel.setMaTre(cbMatre.getSelectedItem().toString());
        hocPhiModel.setTienHP(Double.parseDouble(txtHP.getText()));
        if(rbChuatt.isSelected())
        hocPhiModel.setTtrang("Chưa thanh toán");
        else
        if(rbDatt.isSelected())
        hocPhiModel.setTtrang("Đã thanh toán");
        hocPhiModel.setTienDaDong(Double.parseDouble(txtHPDD.getText()));
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
        String ngthu =dateFormat.format(txtNgaythu.getDate());
        hocPhiModel.setNgayThu(ngthu);
        hocPhiModel.setManv(cbNV.getSelectedItem().toString());
        hocPhiService.addHocPHi(hocPhiModel);
        deTableModel.setRowCount(0);
         List<HocPhiModel> hPhi= hocPhiService.getHocPHi();
        for(HocPhiModel hocPhi : hPhi){
            deTableModel.addRow(new Object[]{hocPhi.getMaHP(), hocPhi.getNgayThu(), hocPhi.getTienHP(), hocPhi.getTienDaDong(), hocPhi.getTtrang(), hocPhi.getMaTre(), hocPhi.getManv()});
        }
        }
      
    }//GEN-LAST:event_addButtonActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_printButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        int row= tableHP.getSelectedRow();
        try {
            hocPhiModel= hocPhiService.getHocPhiByMa(tableHP.getValueAt(row, 0).toString());
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
       String ngthu =dateFormat.format(txtNgaythu.getDate());
      hocPhiModel.setNgayThu(ngthu);
      hocPhiModel.setTienHP(Double.parseDouble(txtHP.getText()));
      hocPhiModel.setTienDaDong(Double.parseDouble(txtHPDD.getText()));
      hocPhiModel.setMaTre(cbMatre.getSelectedItem().toString());
      hocPhiModel.setManv(cbNV.getSelectedItem().toString());
      if(rbChuatt.isSelected())
          hocPhiModel.setTtrang("Chưa thanh toán");
      if(rbDatt.isSelected())
          hocPhiModel.setTtrang("Đã thanh toán");
      hocPhiService.updateHocPhi(hocPhiModel);
      deTableModel.setRowCount(0);
         List<HocPhiModel> hPhi= hocPhiService.getHocPHi();
        for(HocPhiModel hocPhi : hPhi){
            deTableModel.addRow(new Object[]{hocPhi.getMaHP(), hocPhi.getNgayThu(), hocPhi.getTienHP(), hocPhi.getTienDaDong(), hocPhi.getTtrang(), hocPhi.getMaTre(), hocPhi.getManv()});
        }
        } catch (IOException ex) {
            Logger.getLogger(HocPhiPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(HocPhiPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_editButtonActionPerformed

    private void tableHPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableHPMouseClicked
        // TODO add your handling code here:
        int row = tableHP.getSelectedRow();
        String mahp= tableHP.getValueAt(row, 0).toString();
        Date date;
        try {
            date = new SimpleDateFormat("yyyy-MM-dd").parse((String) tableHP.getValueAt(row, 1).toString());
            txtNgaythu.setDate(date);
        } catch (ParseException ex) {
            Logger.getLogger(HocPhiPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
            String tienhp= tableHP.getValueAt(row, 2).toString();
            String tienda= tableHP.getValueAt(row, 3).toString();
            String matre=   tableHP.getValueAt(row, 5).toString();
            String manv= tableHP.getValueAt(row, 6).toString();
            String tinhtrang= tableHP.getValueAt(row, 4).toString();
            if(tinhtrang.equals("Chưa thanh toán"))
            {
                rbChuatt.setSelected(true);
            rbDatt.setSelected(false);
            }
            if(tinhtrang.equals("Đã thanh toán"))
            {
                rbDatt.setSelected(true);
                rbChuatt.setSelected(false);
            }
            txtMaHP.setText(mahp);
            txtHP.setText(tienhp);
            txtHPDD.setText(tienda);
            cbMatre.setSelectedItem(matre);
            cbNV.setSelectedItem(manv);
    }//GEN-LAST:event_tableHPMouseClicked

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
         int row = tableHP.getSelectedRow();
       if(row == -1)
       {
           JOptionPane.showMessageDialog(HocPhiPanel.this,"Vui lòng chọn biên lai để xóa", "Lỗi",JOptionPane.ERROR_MESSAGE);
       }
       else{
           int confirm = JOptionPane.showConfirmDialog(HocPhiPanel.this,"Bạn có chắc muốn xóa không ?");
           if (confirm == JOptionPane.YES_OPTION)
           {
               String mahp = (String) tableHP.getValueAt(row, 0);
               hocPhiService.deleteHocPhi(mahp);
               deTableModel.setRowCount(0);
            List<HocPhiModel> hPhi= hocPhiService.getHocPHi();
        for(HocPhiModel hocPhi : hPhi){
            deTableModel.addRow(new Object[]{hocPhi.getMaHP(), hocPhi.getNgayThu(), hocPhi.getTienHP(), hocPhi.getTienDaDong(), hocPhi.getTtrang(), hocPhi.getMaTre(), hocPhi.getManv()});
        }
           }
       }
    }//GEN-LAST:event_deleteButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbMatre;
    private javax.swing.JComboBox<String> cbNV;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton printButton;
    private javax.swing.JRadioButton rbChuatt;
    private javax.swing.JRadioButton rbDatt;
    private javax.swing.JTable tableHP;
    private javax.swing.JTextField txtHP;
    private javax.swing.JTextField txtHPDD;
    private javax.swing.JTextField txtMaHP;
    private com.toedter.calendar.JDateChooser txtNgaythu;
    // End of variables declaration//GEN-END:variables
}
